from datetime import datetime

from airflow import DAG

from airflow.providers.standard.operators.empty import EmptyOperator
from airflow.providers.standard.operators.python import PythonOperator
from databricks.sdk import WorkspaceClient
import io
import os


CATALOG = "palkin"
SCHEMA = "weather"
VOLUME = "weather_bronze"

def upload_file_to_volume(local_path: str, remote_subpath: str = ""):
    """
    local_path: path to the local file (e.g. downloaded/generated by an upstream task)
    remote_subpath: optional subfolder inside the volume, e.g. "raw/2026-07-24"
    """
    w = WorkspaceClient(
        host=os.environ["DATABRICKS_HOST"],
        token=os.environ["DATABRICKS_TOKEN"],
    )

    filename = os.path.basename(local_path)
    target = f"/Volumes/{CATALOG}/{SCHEMA}/{VOLUME}/{remote_subpath}/{filename}".replace("//", "/")

    with open(local_path, "rb") as f:
        data = f.read()

    w.files.upload(target, io.BytesIO(data), overwrite=True)
    print(f"Uploaded {local_path} -> {target}")





def hello():
    print("Hello Airflow 3")


with DAG(
    dag_id="test_dag",
    start_date=datetime(2026, 1, 1),
    schedule="@daily",
    catchup=False,
) as dag:

    start = EmptyOperator(
        task_id="start"
    )

    python_task = PythonOperator(
        task_id="python_task",
        python_callable=hello
    )

    
    upload_task = PythonOperator(
        task_id="upload_to_volume",
        python_callable=upload_file_to_volume,
        op_kwargs={
            "local_path": "/opt/airflow/data/weather_raw.json",
            "remote_subpath": "{{ ds }}",  # e.g. partitions by execution date
        },
    )

    start >> python_task >> upload_task 