from datetime import datetime , timezone
from airflow import DAG
from airflow.providers.standard.operators.empty import EmptyOperator
from airflow.providers.standard.operators.python import PythonOperator
import json
import requests



from databricks.sdk import WorkspaceClient
import io
import os


CATALOG = "palkin"
SCHEMA = "weather"
VOLUME = "weather_bronze"

def upload_file_to_volume(local_path: str, remote_subpath: str = ""):
    """
    local_path: path to the local file (e.g. downloaded/generated by an upstream task)
    remote_subpath: optional subfolder inside the volume, e.g. "raw/2026-07-24"
    """
    w = WorkspaceClient(
        host=os.environ["DATABRICKS_HOST"],
        token=os.environ["DATABRICKS_TOKEN"],
    )

    filename = os.path.basename(local_path)
    target = f"/Volumes/{CATALOG}/{SCHEMA}/{VOLUME}/{remote_subpath}/{filename}".replace("//", "/")

    with open(local_path, "rb") as f:
        data = f.read()

    w.files.upload(target, io.BytesIO(data), overwrite=True)
    print(f"Uploaded {local_path} -> {target}")



def fetch_from_api(url :str):
    response = requests.get(url)
    if response.status_code == 200:
        data = response.json()
        
    else:
        print(f"Failed to fetch data from API. Status code: {response.status_code}")
    return data


def read_api_data():

    page = 1
    all_records = []
    
    while True:
        url = f"https://www.strictlybetter.eu/api/obsoletes?page={page}"

        payload = fetch_from_api(url)

        print(f"Downloaded page {page}/{payload['last_page']}")

        all_records.extend(payload["data"])

        if page >= 5 :#payload["last_page"]:
            break

        page += 1

    # Save to JSON file
    with open(f"/opt/airflow/data/obsoletes{datetime.now(timezone.utc).strftime('%Y-%m-%d %H-%M')}.json", "w", encoding="utf-8") as f:
        json.dump(all_records, f, indent=4, ensure_ascii=False)

    print(f"\nSaved {len(all_records)} records to obsoletes.json")


with DAG(
    dag_id="data_load_daily",
    start_date=datetime(2026, 1, 1),
    schedule="@hourly",
    catchup=False,
) as dag:

    start = EmptyOperator(
        task_id="start"
    )

    python_task = PythonOperator(
        task_id="python_task",
        python_callable=read_api_data
    )

    end = EmptyOperator(
        task_id="end"
    )
    upload_task = PythonOperator(
            task_id="upload_to_volume",
            python_callable=upload_file_to_volume,
            op_kwargs={
                "local_path": f"/opt/airflow/data/obsoletes{datetime.now(timezone.utc).strftime('%Y-%m-%d %H-%M')}.json",
                "remote_subpath": "{{ ds }}",  # e.g. partitions by execution date
            },
    )

    start >> python_task >> upload_task >> end
